---

- name: CLEAN CONFIG FOLDER
  hosts: all
  connection: local
  gather_facts: no

  vars:
    cliPE:
      host: "lo0-{{inventory_hostname}}"
      username: osainstall
      password: 0sainstall
      transport: cli

  tasks:

########DELETE CONFIG FOLDERS
  - name: Delete target directory
    file: path=configs/{{ CUST_NAME }}/{{SITE_NAME_ALIAS}}-{{ORDER}}/ state=absent
    tags:
    - clearfolder


  - name: ROLLBACK on boot.cfg
    napalm_install_config:
     hostname={{ ansible_host }}
     username=osainstall
     dev_os={{dev_os}}
     password=0sainstall
     config_file=configs/{{ inventory_hostname }}/boot.cfg
     commit_changes=True
     replace_config=True
     get_diffs=True
     diff_file=configs/{{ inventory_hostname }}/{{ inventory_hostname }}.diff
    tags:
    - bootcfg
