---
- name: IPVPN_FABRIC ALL IN ONE PLAYBOOK
  hosts: CUST1
  connection: local
  gather_facts: false

  tasks:
  - name: ROLE GET DATA PE
    include_role:
      name: get_data_pe
    tags:
    - getdatape

  - name: ROLE BGP_PE
    import_role:
      name: bgp_pe
    tags:
    - bgppe

  - name: ROLE VERIFY
    import_role:
      name: verify
    tags:
    - verify

# - import_playbook: BGP_PE.yml
#   tags:
#   - bgppe
#
# - import_playbook: CONFIG.yml
#   tags:
#   - config
#
#
