
- name: IOS_COMMAND AND REGEXP
  hosts: all
  connection: local
  gather_facts: no

  vars:
    cli:
      host: "{{ ansible_host }}"
      username: osainstall
      password: 0sainstall
      transport: cli
    TEMP1: []

  tasks:
  - name: sh ip int brief
    ios_command:
      commands: sh ip int brief
      provider: "{{ cli }}"
    register: shios

  - name: print shiosxr
    debug: var=shios.stdout_lines


  - set_fact:
      TEMP1: "{{ shios.stdout_lines[0] | map('regex_findall','^\\S+')  | map('join') | list }}"


  - name: print TEMP1
    debug: var=TEMP1




  - name: sh ip int brief | i {{REMOTE_WAN}}
    ios_command:
      commands: sh ip int brief | i {{REMOTE_WAN}}
      provider: "{{ cli }}"
    register: shios

  - name: print shiosxr
    debug: var=shios.stdout_lines


  - set_fact:
      TEMP1: "{{ shios.stdout_lines[0] | map('regex_findall','^\\S+')  | map('join') | list }}"


  - name: print TEMP1
    debug: var=TEMP1
