---
- name: IOS_CONFIG TEST
  hosts: all
  connection: local
  gather_facts: no


  tasks:
  - name: push txt in running config
    ios_config:
      #provider: osainstall
      host: "{{ ansible_host }}"
      username: osainstall
      password: 0sainstall
      authorize: yes
      auth_pass: 0sainstall
      transport: cli
      save: no
      src: templates/SNMP_LOCATION.txt
    tags: snmp

  - name: push no txt in running config
    ios_config:
      #provider: osainstall
      host: "{{ ansible_host }}"
      username: osainstall
      password: 0sainstall
      authorize: yes
      auth_pass: 0sainstall
      transport: cli
      save: no
      src: templates/NO_SNMP_LOCATION.txt
    tags: nosnmp
