---
- name: JINJA2 TEMPLATE FOR SNMP LOCATION
  hosts: all
  connection: local
  gather_facts: no


  tasks:


  - name: Create target directory
    file: path=configs/{{ inventory_hostname }}/ state=directory mode=0755

  - name: create SNMP location config
    template: src=templates/SNMP_LOCATION.j2 dest=configs/{{ inventory_hostname }}/SNMP_LOCATION.conf
