---
- name: Get facts
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: get facts from device
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "osainstall"
        dev_os: "{{ dev_os }}"
        password: "0sainstall"
        #filter: ['interfaces','interfaces_ip','arp_table']
        #filter: ['facts']
        #filter: ['arp_table']
        #filter: ['config']
        filter: ['config','interfaces']
        #filter: ['facts','interfaces_ip','bgp_neighbors']
      register: napalm_facts

    - name: Facts
      debug:
        msg: "{{ napalm_facts.ansible_facts }}"
      tags: [print_action]
