
- name: NAPALM_CLI TEST
  hosts: all
  connection: local
  gather_facts: no


  vars:
    TEMP1: []


  tasks:
  - napalm_cli:
      hostname: "{{ ansible_host }}"
      username: "osainstall"
      password: "0sainstall"
      dev_os: "{{dev_os}}"
      args:
          commands:
              - show run
    register: napalmcli


  #- name: Create target directory
  #  file: path=configs/{{ inventory_hostname }}/ state=absent mode=0755

  - name: Create target directory
    file: path=configs/{{ inventory_hostname }}/ state=directory mode=0755

  - copy:
      content: "{{ napalmcli }}"
      dest: "configs/{{ inventory_hostname }}/{{ inventory_hostname }}_napalmcli_ugly.txt"

## now including NICE output Display

  - name: set fact temp = napalmcli.results
    set_fact:
      TEMP1: "{{ item }}"
    with_dict: "{{napalmcli.results}}"

  - name: Display TEMP1.value
    debug: var=TEMP1.value

  - name: reorganize napalm cli output
    set_fact:
      TEMP1: "{{ item }}"
    with_items: "{{TEMP1.value}}"


  - name: print TEMP1
    debug: var=TEMP1

  - copy:
      content: "{{ TEMP1 }}"
      #dest: "configs/{{ inventory_hostname }}/{{ inventory_hostname }}_napalmcli_nice.txt"
      dest: "configs/{{ inventory_hostname }}/boot.cfg"
