
- name: NAPALM_CLI TEST
  hosts: all
  connection: local
  gather_facts: no

  vars:
    TEMP1: []
    TEMP2: []
    TEMP3: []
  tasks:
  - napalm_cli:
      hostname: "{{ ansible_host }}"
      username: "osainstall"
      password: "0sainstall"
      dev_os: "{{dev_os}}"
      optional_args: "transport=telnet"
      args:
          commands:
              - "show ip int brie | i {{REMOTE_WAN}}"
    register: napalmcli

  - name: Display debug
    debug: var=napalmcli.results

  - name: Create target directory
    file: path=configs/{{ inventory_hostname }}/ state=directory mode=0755

  - name: set fact temp = napalmcli.results
    set_fact:
      TEMP1: "{{ item }}"
    with_dict: "{{napalmcli.results}}"

  - name: Display TEMP1.key
    debug: var=TEMP1.key

  - name: Display TEMP1.value
    debug: var=TEMP1.value

  - name: extract interface with split
    set_fact:
      TEMP2: "{{ item.split(' ')[0] }}"
    with_items: "{{TEMP1.value}}"

  - name: Display TEMP2
    debug: var=TEMP2

  - copy:
      content: "{{TEMP2}}"
      dest: "configs/{{ inventory_hostname }}/{{ inventory_hostname }}_napalmcli.txt"
