---

- name: IPVPN_FABRIC VERIFY PLAYBOOK
  hosts: all
  connection: local
  gather_facts: no



  tasks:

########CHECK

  - name: REFRESH BGP sessions
    ios_command:
      commands:
        - clear ip bgp * soft
      host: "{{ COLT_LB.0.IP | ipaddr('address') }}"
      username: osainstall
      password: 0sainstall
      transport: cli
    tags:
    - checkpostSA
    - allinone

  - name: CHECK / Napalm Get Facts from Device
    napalm_get_facts:
      hostname: "{{ COLT_LB.0.IP | ipaddr('address') }}"
      username: "osainstall"
      dev_os: "ios"
      password: "0sainstall"
      filter: ['facts','interfaces_ip','bgp_neighbors']
    register: napalm_facts
    tags:
    - checkpostSA
    - allinone

  - name: CHECK / Print BGP details
    debug:
     msg: "{{ napalm_facts.ansible_facts.napalm_bgp_neighbors.global.peers }}"
    tags:
    - check
    - checkpostSA
    - allinone

########CHECK PING WITH LAN SOURCE
  - name: CHECK / Ping Remote Test IP(s) from source {{ SUBVPN.0.LAN.0.IP }} > {{ SUBVPN.0.LAN.0.IP | regex_replace(' ') }}
    napalm_ping:
      hostname: "{{ COLT_LB.0.IP | ipaddr('address') }}"
      username: "osainstall"
      dev_os: "ios"
      password: "0sainstall"
      source: "{{ SUBVPN.0.LAN.0.IP | regex_replace(' ') | ipaddr('address') }}"
      destination: "{{ item }}"
      count: 5
    with_items: "{{ TEST_IP[SUBVPN.0.NAME] }}"
    register: pingtest
    tags:
    - checkpostSA


  - name: CHECK / print PINGTEST from source {{ SUBVPN.0.LAN.0.IP }}
    debug:
     msg: "{{ pingtest.results | map(attribute='results') | list  }}"
    tags:
    - checkpostSA


########CHECK NAT WITH SH IP NA TR
  - name: CHECK NAT / WITH SH IP NA TR
    ios_command:
      commands: sh ip na tr
      host: "{{ COLT_LB.0.IP | ipaddr('address') }}"
      username: osainstall
      password: 0sainstall
      transport: cli
    register: shipnatr
    tags:
    - checkpostSA
    - shipnatr

  - name: CHECK NAT / Print SH IP NA TR
    debug:
     msg: "{{ shipnatr.stdout_lines }}"
    tags:
    - checkpostSA
    - shipnatr
