---
PUBLIC_MGMT: false
CUST_NAME: CUST
SERVICE_ID: IPC01987
SR: SR_123456
CPE_AS: 65505
CDP_ON_LAN: False
LAN_UP: True
CPE_BGP:
    TIMERS:
        KEEPALIVE: 10
        HOLDTIME: 30
BFD:
    STATUS: no
    INTERVAL:
    MULTIPLIER:
NETFLOW:
    STATUS: no
    VRF: ALL

NETFLOW_DEST: {PROD: 172.20.38.56, TEST: 172.20.38.56}
NETFLOW_SOURCE: Loopback0
NETFLOW_PROTOCOL: V9
NETFLOW_PORT: 9996

EMAIL_DEST_IPCFG:
  PROD: yyy@colt.net
  TEST: xxx@colt.net

EMAIL_DEST_IPTST:
  PROD: yyy@colt.net
  TEST: xxx@colt.net


LAN_2ND_OCTET:
  PROD: { REAL: 223, NAT: 123 }
  TEST: { REAL: 224, NAT: 124 }


TEST_IP:
        PROD:
          - 10.255.1.3
          - 8.8.8.8
        TEST:
          - 172.31.246.254
          - 8.8.8.8

ERX:
    TEST:
        DR1.MAD:
            LB: 10.255.105.99
        DR2.MAD:
            LB: 10.255.105.99
    PROD:
        DR1.PAR:
            LB: 10.255.92.52
        DR2.PAR:
            LB: 10.255.92.52


QOS_PARAM:
    0:
        NAME: 8M
        PR:
            PERCENT: 0
        B1:
            PERCENT: 20
            WRED: yes
            QUEUELIMIT:
        B2:
            PERCENT: 45
            WRED: yes
            QUEUELIMIT:
        B3:
            PERCENT: 0
            WRED: yes
            QUEUELIMIT:
        Def:
            PERCENT: 30
            WRED: yes
            QUEUELIMIT:
    1:
        NAME: 6M
        PR:
            PERCENT: 0
        B1:
            PERCENT: 25
            WRED: yes
            QUEUELIMIT:
        B2:
            PERCENT: 40
            WRED: yes
            QUEUELIMIT:
        B3:
            PERCENT: 0
            WRED: yes
            QUEUELIMIT:
        Def:
            PERCENT: 30
            WRED: yes
            QUEUELIMIT:
