---
ORDER: 'CPE1'
RELATED_ORDER: 'CPE2'
SITE_NAME_ALIAS: SITE1-PRIMARY
SITE_ID: 1
REGION: REGION
COUNTRY: SPAIN
CITY: BARCELONA
STREET: PLAYA
CPE_MODEL: IOSv
COLT_HOSTNAME: CPE1
COLT_LB:
    0:
        IP: 10.255.1.11/32
CUST_HOSTNAME: CUST_CPE1
CUST_LB:
    0:
        ID: 1
        IP: 1.1.1.1/32
        SUBVPN: TEST
ROLE: Spoke
PROVIDER: TELEFONICA
PROVIDER_PRODUCT: SpeedAcceSS bridge 4MB
LINK_ID: MAD/MAD/IA-194201
ACCESS_BW: 10 Mbps
SERVICE_BW:
SAR: PE1
SAR_INT: GigabitEthernet0/0/0/1
SAR_VLAN_FACING_CPE_GRT: 15
GRT_SUBVPN: TEST
GLOBAL_ROUTING_OPTION: ROUTING_EU
SUBVPN:
    0:
        NAME: TEST
        STATUS: Yes
        BW: 4 Mbps
        PE_VLAN:
        QOS_PROFILE: 4M
        WAN:
            0:
                INT:
                VLAN: 15
                IP: 10.253.1.2/30
        LAN:
            0:
                INT:
                VLAN: 0
                MEDIA: RJ45
                SPEED: auto
                DUPLEX: auto
                IP: 10.223.1.252 / 255.255.255.0
                IP_HELPER:
                VIP:
                    0:
                        ID: 1
                        IP: 10.223.1.254 / 255.255.255.0
        B2B:
            0:
                INT: GigabitEthernet0/2
                VLAN: 3
                MEDIA: RJ45
                SPEED: auto
                DUPLEX: auto
                IP: 10.255.80.17/30
