---
ORDER: 'CPE2'
RELATED_ORDER: 'CPE1'
SITE_NAME_ALIAS: SITE1-SECONDARY
SITE_ID: 1
REGION: REGION
COUNTRY: SPAIN
CITY: BARCELONA
STREET: PLAYA
CPE_MODEL: IOSv
COLT_HOSTNAME: CPE2
COLT_LB:
    0:
        IP: 10.255.1.12/32
CUST_HOSTNAME: CUST_CPE2
CUST_LB:
    0:
        ID: 1
        IP: 1.1.1.2/32
        SUBVPN: TEST
ROLE: Resiliency - Dual AcceSS
PROVIDER: TELEFONICA
PROVIDER_PRODUCT: SpeedAcceSS bridge 4MB
LINK_ID: MAD/MAD/IA-194202
ACCESS_BW: 6 Mbps
SERVICE_BW: 2 Mbps
SAR: PE2
SAR_INT: GigabitEthernet0/0/0/1
SAR_VLAN_FACING_CPE_GRT: 25
GRT_SUBVPN: TEST
GLOBAL_ROUTING_OPTION: ROUTING_EU
SUBVPN:
    0:
        NAME: TEST
        STATUS: Yes
        BW: 2 Mbps
        PE_VLAN:
        QOS_PROFILE: 4M
        WAN:
            0:
                INT:
                VLAN: 25
                IP: 10.253.2.2/30
        LAN:
            0:
                INT:
                VLAN: 0
                MEDIA: RJ45
                SPEED: auto
                DUPLEX: auto
                IP: 10.223.1.253 / 255.255.255.0
                IP_HELPER:
                VIP:
                    0:
                        ID: 1
                        IP: 10.223.1.254 / 255.255.255.0
        B2B:
            0:
                INT: GigabitEthernet0/2
                VLAN: 3
                MEDIA: RJ45
                SPEED: auto
                DUPLEX: auto
                IP: 10.255.80.18/30
