---
- name: TS WORKSHOP ANSIBLE EXAMPLE
  hosts: all
  connection: local
  gather_facts: false

  tasks:
  #
  # - name: DEBUG EXAMPLE with hostvars
  #   debug:
  #     msg: "Device {{ inventory_hostname }} is located at {{ LOCATION }}"
  #
  # - name: DEBUG EXAMPLE 2 with groupvars from Groups
  #   debug:
  #     msg: "Device {{ inventory_hostname }} is located at {{ LOCATION }} / {{STREET}} / {{CITY}} / {{COUNTRY}}"
  #
  # - name: DEBUG EXAMPLE 2 with groupvars from Groups
  #   debug:
  #     msg: "{{ inventory_hostname }} SNMP COMMUNITY is {{SNMP.RO_COMMUNITY}}"


#################
  - name: Get Timestamp
    command: date +%Y%m%d-%H%M%S
    register: timestamp
    run_once: true

  - debug:
      msg: "timestamp = {{ timestamp }}"
    run_once: true

  - debug:
      msg: "timestamp in nice YAML format = {{ timestamp | to_nice_yaml }}"
    run_once: true

  - debug:
      msg: "timestamp type is {{ timestamp | type_debug }}"
    run_once: true

  - debug:
      msg: "timestamp.stdout {{ timestamp.stdout }}"
    run_once: true


#################

  # - name: Display all variables/facts known for a host
  #   debug:
  #     var: hostvars[inventory_hostname]
