---
- name: TS WORKSHOP ANSIBLE EXAMPLE
  hosts: all
  connection: local
  gather_facts: false

  tasks:
  - name: IOS DEVICE ping TEST_IPS
    ios_command:
      commands: ping {{item}}
      provider: "{{ cli }}"
    loop: "{{TEST_IPS}}"
    register: pingios
    when: dev_os == "ios"

  - name: print pingios
    debug:
      msg: "{{ item.stdout_lines | to_nice_yaml }}"
    loop: "{{pingios.results}}"
    when: dev_os == "ios"

  - name: EOS DEVICE ping TEST_IPS
    eos_command:
      commands: ping {{item}}
      provider: "{{ cli }}"
    loop: "{{TEST_IPS}}"
    register: pingeos
    when: dev_os == "eos"

  - name: print sheos
    debug:
      msg: "{{ item.stdout_lines | to_nice_yaml }}"
    loop: "{{pingeos.results}}"
    when: dev_os == "eos"

  - name: IOSXR DEVICE ping TEST_IPS
    iosxr_command:
      commands: ping {{item}}
      provider: "{{ cliXR }}"
    loop: "{{TEST_IPS}}"
    register: pingiosxr
    when: dev_os == "iosxr"

  - name: print shiosxr
    debug:
      msg: "{{ item.stdout_lines | to_nice_yaml }}"
    loop: "{{pingiosxr.results}}"
    when: dev_os == "iosxr"
