
- name: IOSXR_COMMAND TEST
  hosts: all
  connection: local
  gather_facts: no

  vars:
    cli:
      host: "{{ ansible_host }}"
      username: osainstall
      password: 0sainstall
      transport: cli

  tasks:
  - name: sh run
    iosxr_command:
      commands: sh run
      provider: "{{ cli }}"
    register: shiosxr

  - name: print shiosxr
    debug: var=shiosxr.stdout_lines
