cli:
  host: lo0-MGMT
  username: osainstall
  password: 0sainstall
  #transport: cli
cliPE:
  host: "lo0-{{SAR_NAME}}"
  username: osainstall
  password: 0sainstall
  #transport: cli
TEMP1: []
MGMT_LB_PE: []
REVERSE_DNS: []
SAR_temp: []
SAR_CITY: []
SAR_NUM: []
SAR_NAME: []
TEMP2: []
TEMP3: []
PE_SUBINT: []
PE_INT: []
PE_VLANID: []
SAR_OS: []
